# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wuDIWTJo5dBd2wHssY5s4VNBB2WEgJmd
"""

print("hello world")

